# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = p14.o
LINKOBJ  = p14.o
LIBS     = -L"D:/programming/dev/Dev-Cpp/MinGW64/lib" -L"D:/programming/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/programming/dev/Dev-Cpp/MinGW64/include" -I"D:/programming/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programming/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/programming/dev/Dev-Cpp/MinGW64/include" -I"D:/programming/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programming/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/programming/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = p14.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

p14.o: p14.c
	$(CC) -c p14.c -o p14.o $(CFLAGS)
